name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels: ['breaking', 'major']
  minor:
    labels: ['enhancement', 'feature', 'minor']
  patch:
    labels: ['bug', 'fix', 'patch', 'chore', 'dependencies']
  default: patch
categories:
  - title: '🚨 Breaking Changes'
    labels: ['breaking', 'major']
  - title: '🚀 Features'
    labels: ['enhancement', 'feature', 'minor']
  - title: '🐛 Bug Fixes'
    labels: ['bug', 'fix', 'patch']
  - title: '🧰 Maintenance'
    labels: ['chore', 'dependencies', 'refactor']
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
