extends:
  - "@commitlint/config-conventional"
rules:
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
      - land
      - brand
      - WIP
      - STAGE1
      - STAGE2
      - STAGE3
  type-case:
    - 0
  type-empty:
    - 0
  subject-empty:
    - 0
  body-max-line-length:
    - 0
