coverage:
  status:
    project:
      agileplus-cli:
        target: 80%
        threshold: 1%
        flags:
          - agileplus-cli
      agileplus-sqlite:
        target: 80%
        threshold: 1%
        flags:
          - agileplus-sqlite
      agileplus-trace-validator:
        target: 80%
        threshold: 1%
        flags:
          - agileplus-trace-validator

flags:
  agileplus-cli:
    paths:
      - crates/agileplus-cli/
  agileplus-sqlite:
    paths:
      - crates/agileplus-sqlite/
  agileplus-trace-validator:
    paths:
      - crates/agileplus-trace-validator/
