[workspace]
changelog_update = true
dependencies_update = true
git_release_enable = true
git_tag_enable = true
pr_name = "chore: release crates"
pr_draft = false
semver_check = false

[[package]]
name = "agileplus"
publish = false
release = false

[[package]]
name = "agileplus-benchmarks"
publish = false
release = false

[[package]]
name = "agileplus-contract-tests"
publish = false
release = false

[[package]]
name = "agileplus-integration-tests"
publish = false
release = false

[[package]]
name = "xtask-anti-patterns"
publish = false
release = false
