//! AgilePlus protobuf messages and gRPC service stubs.
//!
//! Generated by [buf.build] — do not edit manually.
//! Run `buf generate` from the repo root to regenerate.

// Module declarations for generated code will be added when sources are generated.

#[allow(dead_code)]
pub const PLACEHOLDER: &str = "agileplus-proto";

#[cfg(test)]
mod tests {
    #[test]
    fn placeholder_exists() {
        assert_eq!(crate::PLACEHOLDER, "agileplus-proto");
    }
}
