[package]
name = "agileplus-artifacts"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }
base64 = "0.22"
bytes = "1"
chrono = { workspace = true }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_json"]
