[package]
name = "agileplus-grpc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
agileplus-domain = { version = "0.2.1", path = "../agileplus-domain" }
agileplus-proto = { version = "0.2.1", path = "../../rust" }
tonic = { workspace = true }
prost.workspace = true
tokio.workspace = true
tokio-stream = { version = "0.1", features = ["sync"] }
futures = "0.3"
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true

[build-dependencies]
tonic-prost-build = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
