[package]
name = "agileplus-contract-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true

[dev-dependencies]
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true

[package.metadata.dist]
dist = false
