[package]
name = "agileplus-integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
agileplus-domain = { version = "0.2.4", path = "../agileplus-domain" }
agileplus-sqlite = { version = "0.2.4", path = "../agileplus-sqlite" }
agileplus-api = { version = "0.2.4", path = "../agileplus-api" }
tokio.workspace = true
tempfile.workspace = true
async-trait.workspace = true
thiserror.workspace = true
reqwest.workspace = true
serde_json.workspace = true
chrono.workspace = true
rusqlite.workspace = true

[package.metadata.dist]
dist = false
