[package]
name = "agileplus-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Generated gRPC stubs for AgilePlus"

[dependencies]
prost.workspace = true
tonic.workspace = true

[package.metadata.cargo-machete]
ignored = ["prost"]

[build-dependencies]
tonic-build.workspace = true
