#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJ_DIR="$(dirname "$SCRIPT_DIR")"
RUNTIME_DIR="$PROJ_DIR/.agileplus/runtime"
PORTS_FILE="$RUNTIME_DIR/local-ports.env"

mkdir -p "$RUNTIME_DIR"

cat >"$PORTS_FILE" <<EOF
AGILEPLUS_POSTGRES_PORT=5440
AGILEPLUS_REDIS_PORT=6390
AGILEPLUS_NATS_PORT=4231
AGILEPLUS_NATS_HTTP_PORT=8232
AGILEPLUS_NEO4J_PORT=7697
AGILEPLUS_NEO4J_HTTP_PORT=7485
AGILEPLUS_MINIO_PORT=9012
AGILEPLUS_MINIO_CONSOLE_PORT=9013
AGILEPLUS_PLANE_API_PORT=8013
AGILEPLUS_PLANE_WEB_PORT=3113
AGILEPLUS_API_PORT=3014
EOF

source "$PORTS_FILE"
