#!/usr/bin/env python3
"""
run_dag_units.py — DAG Unit Executor for AgilePlus

Reads a DAG manifest (JSON) with unit_ids and for each unit emits:
  - A spec.md following AgilePlus spec conventions
  - A tasks/WP<unit_id>.md following AgilePlus work-package conventions

Usage:
    python scripts/run_dag_units.py <manifest.json> [--output-dir <path>]

The manifest schema:
{
  "epic": "epic_F",
  "title": "DAG foundation + automation",
  "units": [
    {
      "unit_id": "F1",
      "title": "Unit title",
      "type": "automation",
      "description": "What this unit does",
      "dependencies": ["F0"],
      "subtasks": ["T001", "T002"]
    }
  ]
}

Validation: duplicate unit_ids cause an error before any files are written.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def validate_manifest(manifest: dict) -> list[dict]:
    """Validate manifest structure and check for duplicate unit_ids."""
    errors = []
    units = manifest.get("units", [])

    if not isinstance(units, list):
        errors.append("'units' must be a list")
        return errors

    seen_ids = {}
    for i, unit in enumerate(units):
        uid = unit.get("unit_id")
        if not uid or not isinstance(uid, str):
            errors.append(f"unit[{i}]: missing or invalid 'unit_id'")
            continue
        if uid in seen_ids:
            errors.append(
                f"Duplicate unit_id '{uid}' at index {i} "
                f"(first seen at index {seen_ids[uid]})"
            )
        seen_ids[uid] = i

        required = ["title", "type", "description"]
        for field in required:
            if field not in unit or not isinstance(unit[field], str):
                errors.append(f"unit[{i}] ('{uid}'): missing or invalid '{field}'")

    return errors


def generate_spec_md(epic: str, manifest: dict) -> str:
    """Generate a spec.md for the DAG epic."""
    units = manifest.get("units", [])
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        f"# {manifest.get('title', 'DAG Epic')}",
        "",
        f"**Epic:** {epic}",
        f"**Generated:** {now}",
        f"**Status:** Draft",
        f"**Type:** automation",
        "",
        "## Overview",
        "",
        manifest.get("description", ""),
        "",
        "## DAG Units",
        "",
        "| Unit ID | Title | Type | Dependencies |",
        "|---------|-------|------|--------------|",
    ]

    for unit in units:
        deps = ", ".join(unit.get("dependencies", [])) or "—"
        lines.append(
            f"| {unit['unit_id']} | {unit['title']} | "
            f"{unit.get('type', 'automation')} | {deps} |"
        )

    lines += [
        "",
        "## Unit Details",
        "",
    ]

    for unit in units:
        lines.append(f"### {unit['unit_id']}: {unit['title']}")
        lines.append("")
        lines.append(unit.get("description", ""))
        lines.append("")
        subtasks = unit.get("subtasks", [])
        if subtasks:
            lines.append("#### Subtasks")
            for st in subtasks:
                lines.append(f"- [ ] {st}")
            lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def generate_wp_md(unit: dict, epic: str, phase: str) -> str:
    """Generate a work-package .md file for a single DAG unit."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    wp_id = unit["unit_id"]
    deps = unit.get("dependencies", [])
    subtasks = unit.get("subtasks", [])

    frontmatter_lines = [
        "---",
        f'work_package_id: "{wp_id}"',
        f'title: "{unit["title"]}"',
        f'epic: "{epic}"',
        'lane: "planned"',
        f"dependencies: {json.dumps(deps)}",
        f'created_at: "{now}"',
        f"subtasks:",
    ]
    for st in subtasks:
        frontmatter_lines.append(f"  - {st}")
    frontmatter_lines.append(f'phase: "{phase}"')
    frontmatter_lines.append('assignee: ""')
    frontmatter_lines.append('agent: ""')
    frontmatter_lines.append('shell_pid: ""')
    frontmatter_lines.append('review_status: ""')
    frontmatter_lines.append('reviewed_by: ""')
    frontmatter_lines.append("history:")
    frontmatter_lines.append(f'  - timestamp: "{now}"')
    frontmatter_lines.append('    lane: "planned"')
    frontmatter_lines.append('    agent: "system"')
    frontmatter_lines.append('    action: "Generated by run_dag_units.py"')
    frontmatter_lines.append("---")
    frontmatter_lines.append("")

    body_lines = [
        f"# Work Package Prompt: {wp_id} -- {unit['title']}",
        "",
        f"**Epic:** {epic}",
        f"**Type:** {unit.get('type', 'automation')}",
        "",
        "## Description",
        "",
        unit.get("description", ""),
        "",
    ]

    if deps:
        body_lines.append("## Dependencies")
        body_lines.append("")
        for dep in deps:
            body_lines.append(f"- `{dep}`")
        body_lines.append("")

    if subtasks:
        body_lines.append("## Subtasks")
        body_lines.append("")
        for st in subtasks:
            body_lines.append(f"- [ ] {st}")
        body_lines.append("")

    body_lines.append("## Acceptance Criteria")
    body_lines.append("")
    body_lines.append("- [ ] Work package produces expected output")
    body_lines.append("- [ ] All subtasks are completed")
    body_lines.append("- [ ] No regressions introduced")
    body_lines.append("")

    return "\n".join(frontmatter_lines + body_lines)


def generate_tasks_md(units: list[dict], epic: str) -> str:
    """Generate an aggregated tasks.md listing all work packages."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        f"# Work Packages: {epic}",
        "",
        f"**Generated:** {now}",
        "",
        "## Summary",
        "",
        f"Total units: {len(units)}",
        "",
        "| WP ID | Title | Type | Dependencies | Status |",
        "|-------|-------|------|--------------|--------|",
    ]
    for unit in units:
        deps = ", ".join(unit.get("dependencies", [])) or "—"
        lines.append(
            f"| {unit['unit_id']} | {unit['title']} | "
            f"{unit.get('type', 'automation')} | {deps} | planned |"
        )

    lines.append("")
    lines.append("---")
    lines.append("")

    for unit in units:
        wp_id = unit["unit_id"]
        lines.append(f"## Work Package {wp_id}: {unit['title']}")
        lines.append("")
        lines.append(f"**Prompt:** `tasks/WP{wp_id}.md`")
        lines.append("")
        lines.append(unit.get("description", ""))
        lines.append("")
        subtasks = unit.get("subtasks", [])
        if subtasks:
            lines.append("### Subtasks")
            for st in subtasks:
                lines.append(f"- [ ] {st}")
            lines.append("")
        deps = unit.get("dependencies", [])
        if deps:
            lines.append("### Dependencies")
            for dep in deps:
                lines.append(f"- `{dep}`")
            lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Execute DAG units: generate spec.md and WP files from a manifest."
    )
    parser.add_argument("manifest", help="Path to DAG manifest JSON file")
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory for generated files (default: current dir)",
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"Error: manifest file not found: {manifest_path}", file=sys.stderr)
        sys.exit(1)

    with open(manifest_path, "r") as f:
        try:
            manifest = json.load(f)
        except json.JSONDecodeError as e:
            print(f"Error: invalid JSON in manifest: {e}", file=sys.stderr)
            sys.exit(1)

    # Validate
    errors = validate_manifest(manifest)
    if errors:
        print("Manifest validation errors:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        sys.exit(1)

    epic = manifest.get("epic", "unknown-epic")
    units = manifest["units"]
    output_dir = Path(args.output_dir)
    spec_dir = output_dir / "specs" / epic
    tasks_dir = spec_dir / "tasks"

    # Create output directories
    spec_dir.mkdir(parents=True, exist_ok=True)
    tasks_dir.mkdir(parents=True, exist_ok=True)

    print(f"Epic: {epic}")
    print(f"Units: {len(units)}")
    print(f"Output: {spec_dir}")
    print()

    # Generate and write spec.md
    spec_content = generate_spec_md(epic, manifest)
    spec_file = spec_dir / "spec.md"
    spec_file.write_text(spec_content, encoding="utf-8")
    print(f"  [spec]  {spec_file}")

    # Generate and write tasks.md (aggregated index)
    tasks_md_content = generate_tasks_md(units, epic)
    tasks_md_file = spec_dir / "tasks.md"
    tasks_md_file.write_text(tasks_md_content, encoding="utf-8")
    print(f"  [tasks] {tasks_md_file}")

    # Generate individual WP files
    for unit in units:
        wp_content = generate_wp_md(unit, epic, manifest.get("phase", "Phase 1"))
        wp_file = tasks_dir / f"WP{unit['unit_id']}.md"
        wp_file.write_text(wp_content, encoding="utf-8")
        print(f"  [wp]    {wp_file}")

    # Generate meta.json
    meta = {
        "epic": epic,
        "title": manifest.get("title", ""),
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "unit_count": len(units),
        "unit_ids": [u["unit_id"] for u in units],
    }
    meta_file = spec_dir / "meta.json"
    meta_file.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    print(f"  [meta]  {meta_file}")

    print()
    print("Done. All files generated successfully.")


if __name__ == "__main__":
    main()
