// SPDX-License-Identifier: MIT OR Apache-2.0
//! Integration tests for the builder pattern generated by `config_builder!`.
//!
//! Covers field-kind setter semantics: `(str)`, `(opt_str)` and `(val)`,
//! method chaining, `Into<String>` conversions, and mutation isolation.

use agileplus_config::config_builder;

config_builder! {
    #[derive(Clone, Debug, PartialEq)]
    pub struct WebConfig {
        (str)     pub host: String = "localhost".to_string(),
        (val)     pub port: u16 = 8080,
        (opt_str) pub cert_path: Option<String> = None,
        (val)     pub tls: bool = false,
        (val)     pub backlog: usize = 128,
    }
}

config_builder! {
    #[derive(Clone, Debug, PartialEq)]
    pub struct LogConfig {
        (str)     pub level: String = "info".to_string(),
        (str)     pub format: String = "text".to_string(),
        (val)     pub verbose: bool = false,
        (val)     pub max_file_size_mb: u32 = 10,
        (val)     pub rotation_count: u32 = 5,
    }
}

config_builder! {
    #[derive(Clone, Debug, PartialEq)]
    pub struct LimitsConfig {
        (val)     pub max_connections: u32 = 100,
        (val)     pub timeout_secs: u64 = 30,
        (val)     pub shutdown_grace_ms: u64 = 2000,
        (val)     pub retries: u16 = 3,
    }
}

// --- `(str)` setters accept both &str and String ---------------------------------

#[test]
fn str_setter_from_literal() {
    let c = WebConfig::default().with_host("api.example.com");
    assert_eq!(c.host, "api.example.com");
}

#[test]
fn str_setter_from_owned_string() {
    let owned = String::from("internal.example.com");
    let c = WebConfig::default().with_host(owned);
    assert_eq!(c.host, "internal.example.com");
}

#[test]
fn str_setter_from_reference() {
    let s = String::from("ref.example.com");
    let c = WebConfig::default().with_host(&s);
    assert_eq!(c.host, "ref.example.com");
}

#[test]
fn str_setter_empty_string() {
    let c = LogConfig::default().with_level("");
    assert_eq!(c.level, "");
}

#[test]
fn str_setter_unicode() {
    let c = WebConfig::default().with_host("héllo-例");
    assert_eq!(c.host, "héllo-例");
}

// --- `(opt_str)` setters ----------------------------------------------------------

#[test]
fn opt_str_setter_wraps_in_some() {
    let c = WebConfig::default().with_cert_path("/etc/tls/cert.pem");
    assert_eq!(c.cert_path.as_deref(), Some("/etc/tls/cert.pem"));
}

#[test]
fn opt_str_setter_owned_string() {
    let path = String::from("/var/cert.pem");
    let c = WebConfig::default().with_cert_path(path);
    assert_eq!(c.cert_path.as_deref(), Some("/var/cert.pem"));
}

#[test]
fn opt_str_setter_leaves_type_option() {
    let c = WebConfig::default().with_cert_path("x");
    // The field remains an Option<String>, never a bare String.
    let _opt: Option<String> = c.cert_path.clone();
    assert!(c.cert_path.is_some());
}

#[test]
fn opt_str_default_is_none() {
    let c = WebConfig::default();
    assert_eq!(c.cert_path, None);
}

#[test]
fn opt_str_overwrite() {
    let c = WebConfig::default()
        .with_cert_path("first.pem")
        .with_cert_path("second.pem");
    assert_eq!(c.cert_path.as_deref(), Some("second.pem"));
}

// --- `(val)` setters -------------------------------------------------------------

#[test]
fn val_setter_changes_value_leave_others() {
    let c = WebConfig::default().with_port(9000);
    assert_eq!(c.port, 9000);
    assert_eq!(c.host, "localhost"); // untouched
    assert_eq!(c.backlog, 128); // untouched
}

#[test]
fn val_setter_bool_true() {
    let c = WebConfig::default().with_tls(true);
    assert!(c.tls);
}

#[test]
fn val_setter_usize() {
    let c = WebConfig::default().with_backlog(1024);
    assert_eq!(c.backlog, 1024);
}

#[test]
fn val_setter_u32() {
    let c = LogConfig::default().with_max_file_size_mb(500);
    assert_eq!(c.max_file_size_mb, 500);
}

#[test]
fn val_setter_u64() {
    let c = LimitsConfig::default().with_timeout_secs(120);
    assert_eq!(c.timeout_secs, 120);
}

#[test]
fn val_setter_u16() {
    let c = LimitsConfig::default().with_retries(0);
    assert_eq!(c.retries, 0);
}

#[test]
fn val_setter_zero() {
    let c = LimitsConfig::default().with_max_connections(0);
    assert_eq!(c.max_connections, 0);
}

#[test]
fn val_setter_max_values() {
    let c = LimitsConfig::default()
        .with_timeout_secs(u64::MAX)
        .with_shutdown_grace_ms(u64::MAX);
    assert_eq!(c.timeout_secs, u64::MAX);
    assert_eq!(c.shutdown_grace_ms, u64::MAX);
}

// --- Method chaining -------------------------------------------------------------

#[test]
fn chain_all_fields_web() {
    let c = WebConfig::default()
        .with_host("prod.example.com")
        .with_port(443)
        .with_cert_path("/etc/tls.pem")
        .with_tls(true)
        .with_backlog(4096);
    assert_eq!(c.host, "prod.example.com");
    assert_eq!(c.port, 443);
    assert_eq!(c.cert_path.as_deref(), Some("/etc/tls.pem"));
    assert!(c.tls);
    assert_eq!(c.backlog, 4096);
}

#[test]
fn chain_all_fields_log() {
    let c = LogConfig::default()
        .with_level("debug")
        .with_format("json")
        .with_verbose(true);
    assert_eq!(c.level, "debug");
    assert_eq!(c.format, "json");
    assert!(c.verbose);
    assert_eq!(c.max_file_size_mb, 10); // untouched
}

#[test]
fn chain_preserves_defaults_for_unset() {
    let c = LimitsConfig::default().with_max_connections(50);
    assert_eq!(c.max_connections, 50);
    assert_eq!(c.timeout_secs, 30);
    assert_eq!(c.shutdown_grace_ms, 2000);
    assert_eq!(c.retries, 3);
}

// --- Mutation isolation (builder consumed, so each call is fresh) ----------------

#[test]
fn builders_are_independent() {
    let a = WebConfig::default().with_port(1111);
    let b = WebConfig::default().with_port(2222);
    assert_eq!(a.port, 1111);
    assert_eq!(b.port, 2222);
    assert_eq!(a.host, b.host);
}

#[test]
fn default_is_immutable_template() {
    // Building from the default must not mutate the default.
    let _built = WebConfig::default().with_host("changed");
    let fresh = WebConfig::default();
    assert_eq!(fresh.host, "localhost");
    assert_eq!(fresh.port, 8080);
}

// --- Derived trait interactions through the builder ------------------------------

#[test]
fn clone_after_build_equal() {
    let orig = WebConfig::default()
        .with_host("clone-me")
        .with_tls(true);
    let copy = orig.clone();
    assert_eq!(orig, copy);
}

#[test]
fn debug_shows_built_values() {
    let c = WebConfig::default().with_port(8443);
    let d = format!("{c:?}");
    assert!(d.contains("WebConfig"));
    assert!(d.contains("8443"));
}

// --- Defaults from the builder style ----------------------------------------------

#[test]
fn web_defaults() {
    let c = WebConfig::default();
    assert_eq!(c.host, "localhost");
    assert_eq!(c.port, 8080);
    assert_eq!(c.cert_path, None);
    assert!(!c.tls);
    assert_eq!(c.backlog, 128);
}

#[test]
fn log_defaults() {
    let c = LogConfig::default();
    assert_eq!(c.level, "info");
    assert_eq!(c.format, "text");
    assert!(!c.verbose);
    assert_eq!(c.max_file_size_mb, 10);
    assert_eq!(c.rotation_count, 5);
}

#[test]
fn limits_defaults() {
    let c = LimitsConfig::default();
    assert_eq!(c.max_connections, 100);
    assert_eq!(c.timeout_secs, 30);
    assert_eq!(c.shutdown_grace_ms, 2000);
    assert_eq!(c.retries, 3);
}