#!/usr/bin/env python3
"""Regenerate kitty-specs/INDEX.md.

Local validation: run `agileplus validate-encoding --all` after regeneration to
confirm UTF-8 without BOM.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SPEC_ROOT = ROOT / "kitty-specs"
INDEX = SPEC_ROOT / "INDEX.md"
REQUIRED_SPEC_FILES = ("spec.md", "plan.md", "tasks.md", "meta.json")


def render_value(value: Any) -> str:
    if value is None or value == "":
        return "-"
    return str(value)


def load_specs() -> list[dict[str, Any]]:
    specs: list[dict[str, Any]] = []
    for meta_path in sorted(SPEC_ROOT.glob("*/meta.json")):
        with meta_path.open("r", encoding="utf-8-sig") as handle:
            meta = json.load(handle)
        meta["_path"] = meta_path.parent
        specs.append(meta)
    return sorted(specs, key=lambda item: render_value(item.get("spec_id")))


def validate_schema(specs: list[dict[str, Any]]) -> list[str]:
    errors: list[str] = []
    for spec in specs:
        spec_dir = Path(spec["_path"])
        missing = [name for name in REQUIRED_SPEC_FILES if not (spec_dir / name).is_file()]
        if missing:
            errors.append(f"{spec_dir.relative_to(ROOT)} missing {', '.join(missing)}")
    return errors


def render_index(specs: list[dict[str, Any]]) -> str:
    lines = [
        "# Kitty Specs Index",
        "",
        "<!-- Generated by tooling/governance_index.py. Do not edit by hand. -->",
        "",
        "| spec_id | slug | status | created | reactivated | superseded_by | link |",
        "|---|---|---|---|---|---|---|",
    ]
    for spec in specs:
        spec_dir = Path(spec["_path"])
        slug = render_value(spec.get("slug") or spec_dir.name)
        link = f"[{slug}]({spec_dir.name}/spec.md)"
        lines.append(
            "| "
            + " | ".join(
                [
                    render_value(spec.get("spec_id")),
                    slug,
                    render_value(spec.get("status") or spec.get("state")),
                    render_value(spec.get("created_at") or spec.get("created")),
                    render_value(spec.get("reactivated_at") or spec.get("reactivated")),
                    render_value(spec.get("superseded_by")),
                    link,
                ]
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    specs = load_specs()
    INDEX.write_text(render_index(specs), encoding="utf-8")
    if "--check-schema" in sys.argv[1:]:
        errors = validate_schema(specs)
        if errors:
            for error in errors:
                print(f"schema error: {error}")
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
