name: OpenSSF Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '17 3 * * 6'
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15559c51a265e5bde
        with:
          persist-credentials: false

      - uses: ossf/scorecard-action@sebdbf1c91165e231d69b212d33e7a1cac050479
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - uses: actions/upload-artifact@65462800fd760ebe89d21e646d4645c4a39ce18b
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - uses: github/codeql-action/upload-sarif@662472033e021d55d3e11a421db8326578c3f2d9
        with:
          sarif_file: results.sarif
